### ISSUE TITLE
Feature Request: Add FavoriteTweaks to Limitless. It's also open sourced and would make it more seamless for

### ISSUE THREAD

**Issue by theb1g0ne** [JohnCoatesOSS/Limitless#102]
(If you are making a feature request explain what it is, how it would work, why do you think it'd be useful or improve the project or part of it. If you have snippets of code or sketches/mockups please attach them. When you are done, delete the rest of the template.)<br>
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------
…

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://gist.github.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by JohnCoates** [comment]
I feel that you need to expand on this thought
