### ISSUE TITLE
Merge in all of Saurik's commits up until now

### ISSUE THREAD

**Issue by JohnCoates** [JohnCoatesOSS/Limitless#110]
This is going to be fun.

**Comment by JohnCoates** [comment]
I tried a merge but there were so many conflicts that I gave up. This will be done iteratively

**Comment by JohnCoates** [comment]
Last commit by saurik in this fork is this one from October 22nd, 2015: https://github.com/JohnCoatesOSS/Limitless/commit/0193c0d3e1633676d73477d3fb2c2be319e9da1b

First commit I'm looking at for this merge is from March 9th, 2016: https://github.com/JohnCoatesOSS/Limitless/commit/af7a541a90f647596ccf1309d0d77925b8c5f742

cydo has been renamed to runAsSuperuser

I've added an official property to the Paths class that has the application binary path. A check should be added to the future, but Cydia uses a private API for it and I'm avoiding those for resiliency.

commit: https://github.com/JohnCoatesOSS/Limitless/commit/b697593b75b40e1ab0ae82884706d27170fa32de

**Comment by JohnCoates** [comment]
Avoid system headers to compile using macOS 10.12. - Nov 2, 2016
https://github.com/JohnCoatesOSS/Limitless/commit/e67b009f8f8c7b64e3489eedf40b75056fc45a08

Skipping this one, already compiling fine.

**Comment by JohnCoates** [comment]
Fix a typo: verify the objects found, not the set. - Nov 19, 2016
https://github.com/JohnCoatesOSS/Limitless/commit/e0c35524d9e2f829122142790bc6d1ab0c0a7afb

Skipping this one. Code is not present in runAsSuperuser.

**Comment by JohnCoates** [comment]
Fix LogBrowser logic (as it was only for testing). - Dec 26, 2016
https://github.com/JohnCoatesOSS/Limitless/commit/c66799b9a7cc38772cdda9873bee8ca850173e88

I had fixed the NSLog issue, but besides that this brings in two better ways of doing something.

https://github.com/JohnCoatesOSS/Limitless/commit/a9a9efe440093870ee652de1adb5e3c6825197f0

**Comment by JohnCoates** [comment]
Move to CoreTelephony's _CTServerConnectionCreate. - Dec 27, 2016
https://github.com/JohnCoatesOSS/Limitless/commit/019bd407df21b38dc22972771fc8557e45a844d3

What does this do? It allows javascript to get cellular information? I'm skipping it because it uses private APIs and I don't understand the purpose of this.

**Comment by nullpixel** [comment]
:+1: this will help electra

**Comment by JohnCoates** [comment]
Compile Cydia to arm64 by linking with APT 1.4~b1. - Dec 28, 2016
https://github.com/JohnCoatesOSS/Limitless/commit/0209cce51675512f80e740ce45d568ed6d0029c0

I'm not sure why there's different code between 64 bit and 32 bit? Does APT 32 bit remain on an older version?
https://github.com/JohnCoatesOSS/Limitless/commit/0209cce51675512f80e740ce45d568ed6d0029c0#diff-c3a7a7a4b6d0f978dba4976db94969eaR2623

Not switching to fdistream since I already switched that portion of the code to FILE

Not sure what the point of main_store is: https://github.com/JohnCoatesOSS/Limitless/commit/0209cce51675512f80e740ce45d568ed6d0029c0#diff-c3a7a7a4b6d0f978dba4976db94969eaR10222

I suppose a store method has to be included:
https://github.com/JohnCoatesOSS/Limitless/commit/0209cce51675512f80e740ce45d568ed6d0029c0#diff-c3a7a7a4b6d0f978dba4976db94969eaR10580

commit: https://github.com/JohnCoatesOSS/Limitless/commit/c93a5913f8729f9b85813b7de0ffaba483cbebd3

**Comment by nullpixel** [comment]
For apt, see https://git.nito.tv/nitotv/apt

**Comment by JohnCoates** [comment]
Seriously: not a single person actually helped :/. - Dec 30, 2016
https://github.com/JohnCoatesOSS/Limitless/commit/8bd55062b41bb5598bba59417a90b57e720d3e9b

Weird commit message. I had asked Saurik how I could contribute to Cydia and he told me about this issue. So I fixed it and sent him the commits. He promised it'd get integrated.

citations:
https://github.com/JohnCoatesOSS/cydia/tree/bugfix/displayIdentifiers
https://github.com/JohnCoatesOSS/cydia/commit/b50fe87104ff3fa675dd03acc82201525e39c8f4
https://github.com/JohnCoatesOSS/cydia/commit/81d3a7b223e87930e77c5acb8e49bd84f95f25f0

commit: https://github.com/JohnCoatesOSS/Limitless/commit/8bd55062b41bb5598bba59417a90b57e720d3e9b

**Comment by JohnCoates** [comment]
@nullpixel thanks, coolstar gave me a heads up about that repo. Getting APT working stalled the merge, but finally got everything integrated with https://github.com/JohnCoatesOSS/Limitless/commit/c93a5913f8729f9b85813b7de0ffaba483cbebd3

**Comment by JohnCoates** [comment]
Apparently, setlocale never actually did anything. - Dec 30, 2016
https://github.com/JohnCoatesOSS/Limitless/commit/6220fd7da99b2edf6b1c6e98e65b45216a32e7af

Changed some of the code to Objective-C.

commit:https://github.com/JohnCoatesOSS/Limitless/commit/bcc182883adab924a56106d8dc59e2a499a8aaaa

**Comment by JohnCoates** [comment]
Further work to improve language configuration :/. - Dec 30, 2016
https://github.com/JohnCoatesOSS/Limitless/commit/f886c114ebd1027618550e23b2517876a1c20ef6

commit: https://github.com/JohnCoatesOSS/Limitless/commit/f202b7438d19185b4749ba6b032a5bcadaa50b2f

**Comment by JohnCoates** [comment]
Provide more guarantees against merge catastrophe. - Dec 31, 2016
https://github.com/JohnCoatesOSS/Limitless/commit/fec09a82a82c55ef19723940d96cb15e15fc4ed2

commit: https://github.com/JohnCoatesOSS/Limitless/commit/7c9a8a0d835b54373cabbd45364185ceed77af00

**Comment by JohnCoates** [comment]
Fix APT issue where IMS-Hit leads to a full wedge. - Dec 31, 2016
https://github.com/JohnCoatesOSS/Limitless/commit/6f03b6ca6f07c5a032c8e76244c7591f981654b4

skipped

**Comment by JohnCoates** [comment]
strip was enough for Cydia, and this broke bins/*. - Dec 31, 2016
https://github.com/JohnCoatesOSS/Limitless/commit/bcf098f9b52d0ebda7477466a2d21ebc2a9fdc88

skipped

**Comment by JohnCoates** [comment]
APT incorrectly overlaps http and https origin :/. - Jan 27, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/34903f15854bf6a58663da0cc991ac3aa45bba2b

commit: https://github.com/JohnCoatesOSS/Limitless/commit/b09adc63993d6245ad7b683fc78baf94d267fc8b

**Comment by JohnCoates** [comment]
Fix case-insensitive lookup of package Depends :/. - Jan 27, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/109355f19df80de62ab05eec18df8ae15ad423ec

skipped

**Comment by JohnCoates** [comment]
Try to protect firmware.sh against reentrant bugs. - Jan 29, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/ceffc5bc20c1ab16c4d02e1d3ae8fcfb65557797

commit: https://github.com/JohnCoatesOSS/Limitless/commit/4e1ced825a63d00f79638596f72231630b304a3c

**Comment by JohnCoates** [comment]
Cytore values need to be _packed (I got lucky :D). - Jan 29, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/1fe922cd8b76cffdb15eac07f6e686449e1b1469

commit: https://github.com/JohnCoatesOSS/Limitless/commit/80f6d9c665532c729cebfd12b04e2b16fdb4abbd

**Comment by JohnCoates** [comment]
If Cytore fails to allocate an empty file, unlink. - Jan 29, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/7a6e17cff79a3a007a2519bdb676f1be8e937624

commit: https://github.com/JohnCoatesOSS/Limitless/commit/f22e2ab45539bcc56f8f715547d632ed4fb577f5

**Comment by JohnCoates** [comment]
Rewrite error handling in APT to make it saner :/. - Jan 30, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/e5f70bc138d8a794fffa6e33801dba160189001d

skipped

**Comment by JohnCoates** [comment]
Don't strip the binary when releasing beta builds. - Jan 30, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/01c1b94c09355e8ac95086b783a8b141f3d7e4f8

skipped

**Comment by JohnCoates** [comment]
If Cytore failed to save the first block, restart. - Jan 30, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/2f722d4cc3bf949960a3774e2c4d79df1afded95

commit:https://github.com/JohnCoatesOSS/Limitless/commit/beccd4097dc03f78caafcf964b7ed3f6729aaa5c

**Comment by JohnCoates** [comment]
Let's try to avoid making Guillem Jover sad today. - Jan 30, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/069ee7886cc06b3db4a8d67f2a03a2f4e8d30fa6

commit: https://github.com/JohnCoatesOSS/Limitless/commit/d40489e4879fd8fa73972190886291fa4236ecfc

**Comment by JohnCoates** [comment]
Removing a repository was just kind of locking up. - Jan 30, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/6406cc326ee8a4e72afe375db67c6a10c784afeb

commit: https://github.com/JohnCoatesOSS/Limitless/commit/8e25925cdc1c675887e917c6d49adbaf38976234

**Comment by JohnCoates** [comment]
iOS 10.2 claims "Not privileged to stop service.". - Jan 30, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/5652087ef8eac68233426e3675bf26b0c1585d55

Skipped: We're reloading SpringBoard in a better way already.

**Comment by JohnCoates** [comment]
Do not pass -Wl,-segalign,4000 to the arm64 build. - Jan 31, 2017 
https://github.com/JohnCoatesOSS/Limitless/commit/ae975e88affdfae74671885ad2e5af168d98dd95

Skipped: We already don't.

**Comment by JohnCoates** [comment]
Finally found the crazy APT memory corruption bug. - Jan 31, 2017 
https://github.com/JohnCoatesOSS/Limitless/commit/ae3e7be7d3dddffa0f403482aa1240dbe68c1ddb

Skipped: Not using submodules.

**Comment by JohnCoates** [comment]
Fix a crash in NewTag and remove "I am shit" flag. - Jan 31, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/a07675e1d9fe1344f04b9d436c8de174d086c480

Skipped: Not using submodules.

**Comment by JohnCoates** [comment]
For progress JS on iOS 10 to solve race and flash. - Feb 1, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/f9c8848fc9d0b954980f2dbad9d338ded4ad2a1b

commit: 9c5fc09ef8544a4a66e52d67057bc52f0c2b2289

**Comment by JohnCoates** [comment]
Slim result of NewTag and correct cache iterators. - Feb 2, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/5ecd43c35e8a5bb666624af9ab6279ccc78c7cf2

Skipped: Not using submodules.

**Comment by JohnCoates** [comment]
firmware.sh has no assumed "current" directory :/. - Feb 2, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/b1b79d408f3cda3965b8d9087c334f26b7603208

commit: 5eda79be631937bc1302f4b83c9f724eae77f565

**Comment by JohnCoates** [comment]
The default permission from mktemp is only 600 :/. - Feb 2, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/02ccb263caa97381f1eaf9ed305ff57fd7b69734

Skipped

**Comment by JohnCoates** [comment]
Users do not actually have stat (which is stupid). - Feb 2, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/8c346d337c4b10013d1c81c39e4f3d526e9d3049

commit: c28953860e6e2775e1c2b56fb2ee08350d8ff0ab

**Comment by JohnCoates** [comment]
This check was obviously backwards (OMG I'm dumb). - Feb 3, 2017
ed3caba999d35cd2d60025fa24ea2e6e7087b86b

commit: f90c34e45b364ce4d40de1f403f4cd863e840bc0

**Comment by JohnCoates** [comment]
Do not finish:restart if MoveStash did nothing :/. - Feb 3, 2017
ec89f5e6ae3a97b3f4f854f7baa35559e3d55457

commit: 18403d4baae73607d280609994b4560296bb7a31

**Comment by JohnCoates** [comment]
On 64-bit some of these floats are really CGFloat. - Feb 4, 2017
09e03d2385c301e68025da688831f50dd2e3734d

commit: ba008d8d2429c36278e8ad3290466fdea6a4dce7

**Comment by JohnCoates** [comment]
Move more of sysroot's sadness into iPhonePrivate. - Feb 15, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/63755c48fd5fe4f31775e0f38857314879b93f39

Also fixed most warnings.

commit: e9b33843991e7bc574eefa9cb322f00890fd5d2b

**Comment by JohnCoates** [comment]
Use setPageColor instead of messing with scroller. - Feb 15, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/caa861bdca0452534fccc101228458f5cc6f41f2

commit: c507dbb2e9905a787741c2acfe028251c32bd674

**Comment by JohnCoates** [comment]
Hide custom function_ as an implementation detail. - Feb 15, 2017
f274bb0c14b13e0e7bbf65fc5a07f40fcaa482cc

commit: a1565e885469cae1562f6bd67c65008209d9c652

**Comment by JohnCoates** [comment]
This loaded_ hack is hopefully no longer required. - Feb 15, 2017
2f722d4cc3bf949960a3774e2c4d79df1afded95

https://github.com/JohnCoatesOSS/Limitless/commit/8eedf7e7e7afb78df8388ab7692118e6b9f3b466

**Comment by JohnCoates** [comment]
Move private ivars in CyteKit to @implementations. - Feb 15, 2017
f8c9fd4c9a853ca14ac1d1fb123e2e6200879bb4

commit: 759f114733428ce2be17879ec658f752e68d93ad

**Comment by JohnCoates** [comment]
Move some of our clearly shared code into CyteKit. - Feb 16, 2017
7ccc1484ab74ebf5797820bdd24edccfd42aaa50

commit: 3b23b7b4aa06b1be488a91cc999e1385e4c5edb0

**Comment by JohnCoates** [comment]
Cache sorts (really really important for Chinese). - Feb 16, 2017
187cb9203a03e766172b266b8f99bd9b0fd0ba05


commit: 0e23a9e6aae4037e8722066e1f51af4f4c704e9d

**Comment by JohnCoates** [comment]
Amortize linear probing with a binary search sort. - Feb 16, 2017
8f246508d03eb6540bf07f6478cf40cf656a5e1c

Skipped: I don't see where this code is actually used.

**Comment by JohnCoates** [comment]
Avoid sorting packages_ (it is now Foundation :/). - Feb 16, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/5ddde60fb69b9b9d2466044e208977981d2e1fcb

Skipped: Let's revisit this some other time.

**Comment by JohnCoates** [comment]
Make an executive decision to not support regions. - Feb 16, 2017
https://github.com/JohnCoatesOSS/Limitless/commit/bb347c4c58cfcd72dd17be9eeb2fcb8c813140b9

commit: 87a307a8d0d53f3abf467502de8e6f5b730c3e32

**Comment by JohnCoates** [comment]
Do not rely on specific filenames in source cells. - Feb 16, 2017 https://github.com/JohnCoatesOSS/Limitless/commit/018ea8acbdde7f5ee5d68c7431f9f514dcb27714

commit: 8a935019b7d3ffd2b924235e80de4df8ea4d2238

**Comment by JohnCoates** [comment]
Do not rely on specific filenames in source cells. - Feb 16, 2017
018ea8acbdde7f5ee5d68c7431f9f514dcb27714

commit: 8a935019b7d3ffd2b924235e80de4df8ea4d2238

**Comment by JohnCoates** [comment]
Avoid downloading translation files that will 404. - Feb 16, 2017
9ae8969431fe2ece82dbc1ae952f06d8818b8642

Skipped

**Comment by JohnCoates** [comment]
This new code only works if the button is loading. - Feb 16, 2017
2e2229c6d23d2b9a029d6ab1af76d22cfe83f9a6

commit: 858162b2d821eddc8d941621e1351f276ba0787f

**Comment by JohnCoates** [comment]
CyteKit/Application.mm has to have its @interface. - Feb 16, 2017
5479f823a2110820e389a36baa8a100aef2e6485

Skipped

**Comment by JohnCoates** [comment]
cydia.addPipelinedHost was never actually used :D. - Feb 16, 2017
a8ed80cf69a9766c161673ce15c32ae96968d39b

commit: dadd199d0cfc0e3b896f0f7ec9c0478efa65a81c

**Comment by JohnCoates** [comment]
Cydia no longer needs its own Substrate Safe Mode. - Feb 16, 2017
03ef79ee43de8ebf2ddfeb53c30ad3a12bfce517

Skipped

**Comment by JohnCoates** [comment]
Put CydiaURLCache/NSURLConnection hook in CyteKit. - Feb 16, 2017
68df8c0b7bacec286d4798408b5a110bdac88986

Skipped: Revisit this later.

**Comment by JohnCoates** [comment]
Move a bunch of clearly shared logic into CyteKit. - Feb 16, 2017
a3d01a768f0e7f9d5a36b4bcea04458634818863

Skipped: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Avoid counting a package as "lost" multiple times. - Feb 17, 2017
e65eba85e36a518ccad605c715a88b4ee59ce439

commit: dce37dae8ead206730064f2c31695e167cfc4793

**Comment by JohnCoates** [comment]
Trial move some key global variables into CyteKit. - Mar 4, 2017
f3454874c6097225d806fb2fc9f4fb9e19de6abe

Skipped: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Move CyteKit/RegEx.hpp #include to MobileCydia.mm. - Mar 4, 2017
60bd32466fcc4830ee8ff1774cd2e8d5bf390f4a

Skipped

**Comment by JohnCoates** [comment]
Move some code of Window/TabBarController to Cyte. - Mar 5, 2017
217e22f0f4f84e74a3649d5e292c283b0c468b7f

Skipped: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Move cyte diversions and user agents into CyteKit. - Mar 5, 2017
300a26c1c0cdcc6f86880b6d70e7bdf81d210b4b

Skipped: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Rename IsReachable to CyteIsReachable, in CyteKit. - Mar 5, 2017
8658b2df5d752c857807a1f9a652bdc2226ec429

commit: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Add the date to the binary symbol sidestored copy. - Mar 5, 2017
e7783492d5df3db416020d9a4aa5c36222f17ef4

Skipped: No more makefiles

**Comment by JohnCoates** [comment]
Fix the System user-agent component (this rotted). - Mar 5, 2017
8511eb452e6188051960d2d96473a7810f85f5f2

commit: b3d1846729a4cd6e0639bfab8f380035de2bab44

**Comment by JohnCoates** [comment]
Try removing constructor (this is so annoying :/). - Mar 5, 2017
f4f6714a329bf399840b3f9991b310bd17f7bed6

Skipped: CyteKit changes, let's move away from that

**Comment by JohnCoates** [comment]
Remove HostConfig_ (for some finer-grained locks). - Mar 5, 2017
87d58a906a7660760a9f2b2321fb99e72cdf551b

Skipped: The right way to do this is to use atomic properties and immutable objects.

**Comment by JohnCoates** [comment]
Remove more of these global value cache variables. - Mar 5, 2017
35cd98c0a5a9e685cfb7589acc7cdecbd58b4b61

commit: 838d1fc834cae048fc92f2cc5911c986d3ecf771

**Comment by JohnCoates** [comment]
Move most of CydiaObject to CyteKit as CyteObject. - Mar 5, 2017
c2493c4ee87eb8c1acc4c5b9c9494653186e9765

Skipped: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Remove even more global variables (super CyteKit). - Mar 5, 2017
c72556a6183b20b8061a23292f6846f06d4f1614

Removing global variables? Very good.

commit: e145178a3d144750c0c87c84d2c80553d0811b40

**Comment by JohnCoates** [comment]
Try to abstract CydiaURLProtocol as CyteKit class. - Mar 5, 2017
a02d4e989ec1ecf82da7044375b4010f1b572883

Skipped: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
WebDataSource needs to also be in iPhonePrivate.h. - Mar 7, 2017
fd75908cce0497d8638b82870e5bc4ae215b31e3

commit: a6a18370c5e27c40e47b31fa715813d8191cfd72

**Comment by JohnCoates** [comment]
CyteKit: {retain,release}NetworkActivityIndicator. - Mar 7, 2017
2b5ceba288a3a3de4bceb6767953972b30f97f46

Skipped: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Split PackageListController partially for CyteKit. - Mar 7, 2017
3a6f9c89e5edc675d5741eb5aa66e30e798fb3aa

Skipped: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Also move ListController title support to CyteKit. - Mar 7, 2017
70d35e1385a7311e310a9890ecb163d97bbdf6e9

Skipped: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Port FileTable to the CyteKit ListController type. - Mar 7, 2017
b06c11a9a99fab3c65a793cc2deb020a3e762311

Skipped: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Transfer shared content code to CyteTableViewCell. - Mar 11, 2017
2db33ea12fcfa87654ecf0ba54db21786f1fe821

commit: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Support compound user-agents using CyteInitialize. - Mar 11, 2017
d60043e4dfdcd8321f94720ef885c55ad59a2b3d

commit: Let's move away from CyteKit

**Comment by JohnCoates** [comment]
Do not crash if Safari's Info.plist can't be read. - Mar 11, 2017
03191d515b8474764cc2a34dcc2284fcd158bce6

commit: d411ea91d8159ddec2600b5c716dc8c74120d3ea

**Comment by JohnCoates** [comment]
That was fun, let's do it again real soon.
