### ISSUE TITLE
"Limitless" Needs to Be Updated

### ISSUE THREAD

**Issue by bqrichards** [JohnCoatesOSS/Limitless#111]
What are the steps to reproduce this issue?
-------------------------------------------
1. Jailbreak using Electra 1.0.2
2. Download 'Limitless' app from getdelta.co repo on Cydia
3. Attempt to launch the application

What happens?
-------------
Popup stating "The developer of this app needs to update it to work with iOS 11"

What were you expecting to happen?
----------------------------------
App launch

Any other comments?
-------------------
I thought I heard something about apps needing to be 64 bit to run on iOS 11, that could be it. Didn't expect it to work as the iOS 11 jailbreak just came out two days ago, but thought I'd report it anyway.

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 11.1.2
**Limitless** 1.0~Beta6

**Comment by JohnCoates** [comment]
Working on it: https://github.com/JohnCoatesOSS/Limitless/issues/110
