### ISSUE TITLE
Resolve deprecated warnings

### ISSUE THREAD

**Issue by JohnCoates** [JohnCoatesOSS/Limitless#12]
Moving the deployment target from iOS 2.0 to iOS 8.0 has brought on a lot of deprecated warnings. We need to move all this code to the newer APIs.

![screen shot 2016-11-27 at 2 41 29 pm](https://cloud.githubusercontent.com/assets/967800/20652524/c2cebaee-b4af-11e6-9694-b60d96289067.png)

**Comment by ninjaprawn** [comment]
Just a note to anyone not in the Gitter: This is currently in progress (https://gitter.im/JohnCoatesOSS/Limitless?at=583e388673abd79c55b300b5)

**Comment by JohnCoates** [comment]
All deprecated method warnings removed.
