### ISSUE TITLE
[Concept] Cydia While Sandboxed

### ISSUE THREAD

**Issue by Shugabuga** [JohnCoatesOSS/Limitless#13]
I don't know if this is the best place to put this but I have an outlandish idea. What if Cydia could install packages while sandboxed? There are currently services that offer code signing, as with other stores (like iOSEmus) that maintain a "hub" of signed IPAs you can sideload without a jailbreak, so it may be interesting if we can allow for both of these services to make special Cydia repos that are for unjailbroken devices.

### "Unjailbroken" packages

An "unjailbroken" package would be something that can do the following in place of installing:

1) Check if package is unjailbroken with special flag in the `Control` file of a package exists (like seen below). Icons/description/etc. could all be as it was before and would work as-is

```
unjailbroken: https://repo.example.com/ipa/youtube.plist
```

2) Initiate a web request to a URL in the "unjailbroken" field, returning a dialog to install the remote IPA. It could look something like this (just whipped this render up quickly, I know it's terrible)

<img width="487" alt="screen shot 2016-11-27 at 8 04 03 pm" src="https://cloud.githubusercontent.com/assets/10801851/20653561/62ffc5b2-b4dd-11e6-8711-d1026b8abc95.png">

3) Once you press "Done," it could add it as an "installed" package and if an update is detected on the repo, request an update (that just reinstalls the package). Updating could work just like normal updates.

---

This is just an idea, and an outlandish one at that. Just wanted to share it, as it could give some validity for having Limitless working without root (besides for testing).

**Comment by JohnCoates** [comment]
This would be amazing! I don't have any experience with sideloading, but if this is possible we should definitely make it happen.

**Comment by nathanaccidentally** [comment]
I like this! Hope this gets added! 👍

**Comment by Shugabuga** [comment]
@JohnCoates Sideloading has two main forms: Cydia Impactor (and Xcode) and OTA distribution.

Cydia Impactor is the cheapest way for the end-user and uses the user's Apple ID to code sign the IPA for a week. OTA distribution, however, relies on a third-party to code sign (which is usually via a paid service like iPAStore, but there are free solutions like iOSEmus). This OTA solution would be how we implement our install system (in theory).

What would have to happen is that we make a web request to a .plist file (that defines the OTA install) defined by the repo operator, which would request to download an IPA file to the device until it is revoked. In other words, it would be a package that just makes a GET request or something of the sort. I'm also sure that if Limitless can process `preinst` files while sandboxed, we would just need to document on how to make the needed web requests to initiate an install without jailbreak. Now does `preinst`/`postinst`/etc. files do stuff outside of the sandbox? I'm assuming that it does.

**Comment by JohnCoates** [comment]
Can we implement the functionality of Cydia Impactor? That way the user code signs their own package.

**Comment by Shugabuga** [comment]
In theory? Maybe, but we would need to do a few things before install:

1) Download IPA file

2) Get user's Apple ID information (for code sign)

3) Codesign the IPA somehow.

4) Generate new PLIST

5) Set up web server to host new IPA and PLIST files

6) Make GET request, display install dialog, etc.

7) One week later: Rinse and repeat

If we can do something as crazy as code signing on device, we can theoretically use it to infinitely sign Limitless weekly, so the user would only have to run Cydia Impactor once.

Also, this is a concept (and how it would theoretically work), so you may want to label it as such ("Help Needed"?). I suck at Obj-C, so sorry if you assumed I was working on this.

**Comment by MiRO92** [comment]
Great, i really liked it

**Comment by nullpixel** [comment]
@JohnCoates This is do-able, 110%: r/sideloaded could help with this?

**Comment by JohnCoates** [comment]
This is definitely an awesome feature idea, but being that it would require significant research to pull off, I'm going to label it as Moonshot and close it for now. If someone is willing to take up this project, please let me know.

**Comment by Shugabuga** [comment]
Okay. Thanks for fixing the labels ("approved feature" made it seem like it's in the works when it's a concept and nothing more at the moment). I think @nullpixel1 and others at /r/sideloaded mentioned that they want to help, but I don't know if they wanted to start on other things first (which they should, since this wouldn't be able to be tested until #9 and #1 are fixed) or they don't want to do it at all (it would be one of the hardest features to implement, after all).
