### ISSUE TITLE
[BUG] Sources not showing up + On launch error code

### ISSUE THREAD

**Issue by Dextersmith** [JohnCoatesOSS/Limitless#14]
I am running iOS 9.3.3 on an iPhone 6s Plus 128GB, installed Limitless from the getdelta repo and launched limitless after manually respringing. Upon launch I got this error message:

http://imgur.com/sH4aZOb

Then when I went to look at my sources in Limitless, I did not have the sources I manually added in Cydia, I only had the default ones.

**Comment by JohnCoates** [comment]
Okay, I believe it thinks you're sandboxed. I should be able to patch this pretty quickly, give me a few minutes.

**Comment by Dextersmith** [comment]
Sounds good, awesome work by the way, I will keep submitting bugs as long as I find them. I have not tried out Limitless yet, but is the loading time when adding tweaks shorter than Cydia?

**Comment by JohnCoates** [comment]
It's probably not shorter. We'll see what we can do though. If you could try the latest beta to see if this issue persists that would be great.

**Comment by Dextersmith** [comment]
It's working perfectly now. The icons on some, not all, of the installed tweaks does not show on Limitless, but does on Cydia.

**Comment by JohnCoates** [comment]
Okay awesome. If you could open a new issue with the icon bug along with a screenshot that would be great!
