### ISSUE TITLE
Backup/Restore sources/packages

### ISSUE THREAD

**Issue by MiRO92** [JohnCoatesOSS/Limitless#17]
Please add Backup/Restore sources/packages same as CyDown

**Comment by JohnCoates** [comment]
How does this work? Are they stored in Dropbox?

**Comment by Ankiiii** [comment]
That would be nice. Just link the account to a Dropbox to backup the packages to.

**Comment by Kfeavel** [comment]
Dropbox is on the way out. Honestly, something like Google Drive would be better since Cydia already has support for logging in with Google to keep track of purchases.

**Comment by JohnCoates** [comment]
I'm closing this issue since it hasn't gotten any traction. It'd be a nice feature to have, so I'm labeling it with "feature request" and anyone is welcome to take up the task.
