### ISSUE TITLE
Ability to Tap and hold on any Source to copy it

### ISSUE THREAD

**Issue by MiRO92** [JohnCoatesOSS/Limitless#18]
Please add the ability to Tap and hold on any Source to copy it.

**Comment by uroboro** [comment]
How about make it so it opens the Share menu?

**Comment by MiRO92** [comment]
Yea, that would be much better 👍

**Comment by JohnCoates** [comment]
Shade-Zepheri is working on this https://gitter.im/JohnCoatesOSS/Limitless?at=583d038d8255fe6b76dec742
