### ISSUE TITLE
Cydia should have a dedicated "Featured" Tab.

### ISSUE THREAD

**Issue by Zabir2008** [JohnCoatesOSS/Limitless#2]
Guys I think **Cydia** should get a brand new overhaul and in terms of UI and a brand new icon as well and it should receive a **Featured** tab to showcase great **THEMES** and **TWEAKS** what say ?

**Comment by JohnCoates** [comment]
This issues hasn't gotten any traction in the last few weeks, so I'm closing it. I recommend you bring it up in the redesign concepts issue #28
