### ISSUE TITLE
[Concept Idea] 3D Touch and Cydia Notifications.

### ISSUE THREAD

**Issue by Ankiiii** [JohnCoatesOSS/Limitless#20]
This is probably a bad place to put this but it wasn't letting me creating a new pull request.
Anyways, my general idea is - what if Cydia had 3D Touch of packages? You'd just invoke 3D Touch on a package within Cydia and it comes up with options to install, update, and remove. That by itself seemed like an amazing idea.

I am the type of person who usually likes to keep everything updated. I love getting notifications for new updates on things but with Cydia, there are no pushed notifications to let everyone that there are updates for installed packages. These two ideas seemed the best to me.

**Comment by JohnCoates** [comment]
As far as 3D touch, we've got that in progress at https://github.com/JohnCoatesOSS/Limitless/pull/10 - Not sure what that entails yet as I haven't had a chance to test it out.

I like the notifications idea, but I'm not sure how technically feasible it would be. If anyone has any ideas on how to accomplish this I'd like to hear them.

**Comment by bolencki13** [comment]
Background refresh would get this done, would impact battery life though. The other idea is to have a deeper repo integration that would have server side to push it to the iOS device. A separate library to handle server side requests with pushes. This would also impact battery life. Probably not as much as the first option.

**Comment by ZeusDos** [comment]
Ask for help to the author of : [Release] Tactful - 3D Touch Support for Cydia (BigBoss, free)
http://cydia.saurik.com/package/com.sharedroutine.tactful

**Comment by JohnCoates** [comment]
ninjaprawn has peek+pop underway, he shared this video: https://files.gitter.im/JohnCoatesOSS/Limitless/VTHi/limitless3d.mov

**Comment by JohnCoates** [comment]
3D touching a package right now will pop up a preview of it.
Notifications I feel are a cool idea.
I'm closing this issue since it hasn't gotten any traction. Since it hasn't gotten any traction, I'm closing this issue and labeling it with "feature request". Anyone is welcome to take up the task.
