### ISSUE TITLE
Free tweaks

### ISSUE THREAD

**Issue by mattkk25** [JohnCoatesOSS/Limitless#21]
Instead of paying for tweaks like in cydia, everything should be free

**Comment by Ankiiii** [comment]
I like this idea.

**Comment by JohnCoates** [comment]
So don't allow paid tweaks? Do you have reasoning behind why we should limit it to free tweaks?

**Comment by nathanaccidentally** [comment]
That makes no sense. There is no reason not to allow paid tweaks.

**Comment by Shugabuga** [comment]
But why? This would just hurt the jailbreak community. With paid tweaks come better and more numerous tweaks.

**Comment by JohnCoates** [comment]
I'm going to go ahead an close this issue. This does not close it off to further comments. If reasoning is added to back up this idea I'd be happy to open the issue again.
