### ISSUE TITLE
Change control file's author to reflect community driven project

### ISSUE THREAD

**Issue by JohnCoates** [JohnCoatesOSS/Limitless#25]
Right now the author on the control file is Saurik, since he created Cydia. However since when this project is hosted on a repo we should be have the author reflect that this fork is a community project, and that Saurik shouldn't get bothered about bugs in our project, a change is in order. I'm thinking listing author as "Community Project". I'm happy to list my e-mail so that I can reply to inquires, but if there are any volunteers that have a history of moderating community projects or are otherwise trusted and can provide friendly e-mail replies I'm open to that too.
I'm against setting the author to "Limitless Team" since that provokes a feeling of exclusivity that I wish to avoid, since the project is 100% open.

**Comment by rweichler** [comment]
Maybe it would be better to have the email point to some sort of bot that posts it in a public record somewhere?

Edit: Wait, actually, I think a listserv would be perfect for this

Edit2: Maybe host it on https://www.freelists.org/ ?

**Comment by JohnCoates** [comment]
That might be a good idea, but a more privacy focused approach would be good to consider. I feel the best option would be to find a free help desk service so support tickets are created as e-mails comes in and then handled by volunteers. I feel that when you contact the support e-mail you should expect a bit of privacy, and not have your name & e-mail exposed, or your device UDID and list of installed packages since Cydia attaches those.

Also, here's a link to the relevant chat discussion: https://gitter.im/JohnCoatesOSS/Limitless?at=583cc57d16207f7b0eb921c8

**Comment by JohnCoates** [comment]
Author has been changed in control file to "Jailbreak Community", so I'm closing this issue. If anyone finds a help desk solution feel free to comment.
