### ISSUE TITLE
Better browser support in Cydia

### ISSUE THREAD

**Issue by dyarfaradj** [JohnCoatesOSS/Limitless#3]
Whenever you go to jailbreak reddit from the start page of Cydia you don't get any controls like "Back, forwrad" etc like a twitters browser has.

**Comment by rweichler** [comment]
I think we should just get rid of webviews entirely.

**Comment by JohnCoates** [comment]
We can't get rid of webviews because they provide a lot of functionality. Repos have customized pages, and depend on ads. We can provide an alternative though, for repos that don't do depictions or that opt into another system.

**Comment by rweichler** [comment]
The ads are why I think we should get rid of webviews. I think the old guard of ad-supported repo hosting is long gone, with github pages and whatnot. I think a simple markdown renderer would be just fine

**Comment by JohnCoates** [comment]
More options are definitely better, but no need to remove support for current repos. Are you interested in writing a spec for how repos should work? Maybe JSON?

**Comment by rweichler** [comment]
Yeah I might be, still poking around the code...

And JSON as opposed to Packages.bz2? Wouldn't that break compatibility with dpkg?

**Comment by JohnCoates** [comment]
Yes a JSON instead of a Packages.bz2. We could support both formats.

**Comment by kirb** [comment]
The Reddit link really should have always used `target="_open"` so it'd open in Safari (or Safari view controller now).

**Comment by JohnCoates** [comment]
I'm closing this issue since it hasn't gotten any traction. It'd be a nice feature to have, so I'm labeling it with "feature request" and anyone is welcome to take up the task.
