### ISSUE TITLE
Add in app browser (SafariViewController)

### ISSUE THREAD

**Issue by nathanaccidentally** [JohnCoatesOSS/Limitless#39]
This would be helpful when clicking a link in a depiction or description so that we can view the links with out leaving the app. This has always bugged me with Cydia.

**Comment by kirb** [comment]
It's not really possible for Limitless to be able to guess when it should and shouldn't do this. Really the repos should be using target="_open" on their links. This has been available for a long time, but maybe they just don't know it exists. Contact them and let them know!

**Comment by kirb** [comment]
Didn’t read the title before – this was implemented in #22.
