### ISSUE TITLE
Resprings the right way

### ISSUE THREAD

**Issue by JohnCoates** [JohnCoatesOSS/Limitless#4]
As per /u/ffiresnake's comment: https://www.reddit.com/r/jailbreak/comments/5dpq84/discussion_for_the_last_five_months_ive_been/da6s9ib/

https://gist.github.com/kirb/6149827

**Comment by ninjaprawn** [comment]
See https://gitter.im/JohnCoatesOSS/Limitless?at=583d35a08255fe6b76dfb6aa

**Comment by JohnCoates** [comment]
I'm starting on this.

**Comment by JohnCoates** [comment]
Code is now integrated as of #51, opening up a design issue in case anyone wants to remix the design or try their hand at it.
