### ISSUE TITLE
Warning for uninstalling limitless dependencies.

### ISSUE THREAD

**Issue by EricLegend** [JohnCoatesOSS/Limitless#40]
Feels like everyday on r/Jailbreak someone new asks about how to get cydia back when they deleted cydia installer or any other needed dependencies. I made this quick mock up just on the spot http://i.imgur.com/6rUclMj.jpg. To achieve this maybe you can check the package ID to an array and if it equals something in the array it'll show the UIAlert. Have a good day/night.

**Comment by kirb** [comment]
This already exists – people just ignore the warnings :/

![img_0152](https://cloud.githubusercontent.com/assets/773309/20745162/ea92d22c-b72f-11e6-8256-1103482e967f.png)

**Comment by EricLegend** [comment]
oh, welp nevermind then.
