### ISSUE TITLE
New "Account" section preview

### ISSUE THREAD

**Issue by Sn0wCooder** [JohnCoatesOSS/Limitless#6]
Like [this](https://www.reddit.com/r/jailbreak/comments/569b9x/request_please_saurik_update_the_cydia_account/?)

**Comment by Shugabuga** [comment]
[Link to Concept](http://dylanduff.github.io/Cydia-Account-Page-Alternative/)

**Comment by JohnCoates** [comment]
That looks awesome! Looks like /u/MataNataM created the original concept
https://www.reddit.com/r/jailbreak/comments/4d87cu/discussion_a_reimagined_cydia_my_account_page_i/ - I'll link him back to this issue and see if he'd be interested in collaborating

**Comment by JohnCoates** [comment]
I'm closing this issue, since @MataNataM has started contributing concepts and we're now discussing redesigns in #28
