### ISSUE TITLE
Compatibility with current Cydia Tweaks?

### ISSUE THREAD

**Issue by JoelPeterPage** [JohnCoatesOSS/Limitless#74]
I use:

Flame (Auto Cydia finishing & colours)
Dismiss Progress 
Swipe for More

I would love to see these small tweaks either compatible or incorporated into Limitless!

Adit Kamath develops Flame, I think Poom makes the other two..

**Comment by ThijmenDam** [comment]
Tactful's features would be great as well!

**Comment by JohnCoates** [comment]
Discussion of integrating these tweaks is happening in #23, so I'm closing this issue.
