### ISSUE TITLE
Can I sideload Limitless to my unjailbroken iPhone 7 just to follow tweak updates?

### ISSUE THREAD

**Issue by DaniWinter** [JohnCoatesOSS/Limitless#75]
If so, can you compile it to an IPA?

**Comment by JohnCoates** [comment]
Not possible yet. Limitless can't run sandboxed until the APT replacement discussed in issue #1 is implemented

**Comment by Shugabuga** [comment]
Like @JohnCoates said, you can't as of right now. Until #1 is done, it would just crash on launch.

Your best bet is the Simulator for now.

**Comment by JohnCoates** [comment]
Right now Limitless won't even run in sandbox until #9 is fixed. I'm closing this issue until both references issues are fixed.
