### ISSUE TITLE
[Not Really a Request] Original source code

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [JohnCoatesOSS/Limitless#94]
Can I get the _original_ source code for Limitless? Just plain Cydia, nothing else

**Comment by uroboro** [comment]
It's rather easy to find, even the first link on an incognito search of "cydia source code". http://gitweb.saurik.com/cydia.git

**Comment by JohnCoates** [comment]
If you want plain Cydia, but with an Xcode project added for easier compiling, check out https://github.com/JohnCoatesOSS/Limitless/tree/cydia/master
